//   *****************************************************************************************************************************************
//   ****   PLEASE NOTE: This is a READ-ONLY representation of the actual script. For editing please press the "Develop Script" button.   ****
//   *****************************************************************************************************************************************

Action()
{
	lr_start_transaction("01_Launch");
	truclient_step("1", "Navigate to 'https://spectrumenterprise.net/login'", "snapshot=Action_1.inf");
	truclient_step("2", "Wait for Sign In button", "snapshot=Action_2.inf");
	lr_end_transaction("01_Launch",0);
	truclient_step("3", "Reload current page", "snapshot=Action_3.inf");
	truclient_step("4", "Type Username1 in Username emailbox", "snapshot=Action_4.inf");
	truclient_step("5", "Type ******** in Password passwordbox", "snapshot=Action_5.inf");
	lr_start_transaction("02_Login");
	truclient_step("6", "Click on Sign In button", "snapshot=Action_6.inf");
	lr_end_transaction("02_Login",0);
	truclient_step("7", "Wait for All Network Services", "snapshot=Action_7.inf");
	truclient_step("8", "Click on All Network Services", "snapshot=Action_8.inf");
	truclient_step("9", "Click on EVPL", "snapshot=Action_9.inf");
	lr_start_transaction("03_EVPL Circuit Utilization");
	truclient_step("10", "Click on 1915 Hill St cell", "snapshot=Action_10.inf");
	truclient_step("11", "Wait for Utilization heading", "snapshot=Action_11.inf");
	lr_end_transaction("03_EVPL Circuit Utilization",0);
	lr_start_transaction("04_EVPL Service Availability");
	truclient_step("12", "Click on Service Availability", "snapshot=Action_12.inf");
	truclient_step("13", "Wait for Service Availability heading", "snapshot=Action_13.inf");
	lr_end_transaction("04_EVPL Service Availability",0);
	truclient_step("14", "Click on Back link", "snapshot=Action_14.inf");
	truclient_step("15", "Click on All Network Services", "snapshot=Action_15.inf");
	truclient_step("16", "Click on EP LAN", "snapshot=Action_16.inf");
	lr_start_transaction("07_EP-LAN Circuit Utilization");
	truclient_step("17", "Click on 1014 Corporate Park Dr cell", "snapshot=Action_17.inf");
	truclient_step("18", "Wait for Utilization heading", "snapshot=Action_18.inf");
	lr_end_transaction("07_EP-LAN Circuit Utilization",0);
	lr_start_transaction("08_EP-LAN Service Availability");
	truclient_step("19", "Click on Service Availability", "snapshot=Action_19.inf");
	truclient_step("20", "Wait for Service Availability heading", "snapshot=Action_20.inf");
	lr_end_transaction("08_EP-LAN Service Availability",0);
	truclient_step("21", "Click on Back link", "snapshot=Action_21.inf");
	truclient_step("22", "Click on All Network Services", "snapshot=Action_22.inf");
	truclient_step("23", "Click on EVPL", "snapshot=Action_23.inf");
	truclient_step("24", "Click on 1915 Hill St cell", "snapshot=Action_24.inf");
	truclient_step("25", "Wait for Utilization heading", "snapshot=Action_25.inf");
	lr_start_transaction("09_Network Circuit Create a Report");
	truclient_step("26", "Click on link (1) link", "snapshot=Action_26.inf");
	lr_end_transaction("09_Network Circuit Create a Report",0);
	truclient_step("27", "Scroll on Fill Page", "snapshot=Action_27.inf");
	truclient_step("28", "Click on Last 30 days", "snapshot=Action_28.inf");
	lr_start_transaction("10_Network Circuit Generate Report");
	truclient_step("29", "Click on Submit button", "snapshot=Action_29.inf");
	lr_end_transaction("10_Network Circuit Generate Report",0);
	truclient_step("30", "Click on Go Download Reports link", "snapshot=Action_30.inf");
	truclient_step("31", "Click on LOCATIONS link", "snapshot=Action_31.inf");
	truclient_step("32", "Click on All Network Services", "snapshot=Action_32.inf");
	truclient_step("33", "Click on SD WAN", "snapshot=Action_33.inf");
	lr_start_transaction("05_SDWAN Circuit Utilization");
	truclient_step("34", "Click on 366 N Lake Ave cell", "snapshot=Action_34.inf");
	truclient_step("35", "Wait for Utilization heading", "snapshot=Action_35.inf");
	lr_end_transaction("05_SDWAN Circuit Utilization",0);
	lr_start_transaction("06_SDWAN Network Utilization");
	truclient_step("36", "Click on Network Overview link", "snapshot=Action_36.inf");
	lr_end_transaction("06_SDWAN Network Utilization",0);
	truclient_step("37", "Wait for Fiber Internet link", "snapshot=Action_37.inf");
	lr_start_transaction("11_Fiber Internet Tab");
	truclient_step("38", "Click on Fiber Internet link", "snapshot=Action_38.inf");
	truclient_step("39", "Wait for Address listitem", "snapshot=Action_39.inf");
	lr_end_transaction("11_Fiber Internet Tab",0);
	lr_start_transaction("12_FI Circuit Utilization");
	truclient_step("40", "Click on 105 Wolfpack Rd cell", "snapshot=Action_40.inf");
	truclient_step("41", "Wait for Bandwidth: 25 Mbps", "snapshot=Action_41.inf");
	truclient_step("42", "Wait for Upstream", "snapshot=Action_42.inf");
	lr_end_transaction("12_FI Circuit Utilization",0);
	truclient_step("43", "Click on link (1) link", "snapshot=Action_43.inf");
	truclient_step("44", "Click on Last 30 days", "snapshot=Action_44.inf");
	lr_start_transaction("13_FI Circuit Utilization Report");
	truclient_step("45", "Click on Submit button", "snapshot=Action_45.inf");
	truclient_step("46", "Wait for Go Download Reports link", "snapshot=Action_46.inf");
	lr_end_transaction("13_FI Circuit Utilization Report",0);
	truclient_step("47", "Click on Close Button button", "snapshot=Action_47.inf");
	truclient_step("48", "Click on We're Preparing Your... button", "snapshot=Action_48.inf");
	truclient_step("49", "Click on Back link", "snapshot=Action_49.inf");
	truclient_step("50", "Click on LOCATIONS link", "snapshot=Action_50.inf");
	truclient_step("51", "Wait for REPORTS link", "snapshot=Action_51.inf");
	lr_start_transaction("29_Reports tab");
	truclient_step("52", "Click on REPORTS link", "snapshot=Action_52.inf");
	truclient_step("53", "Wait for Created By", "snapshot=Action_53.inf");
	lr_end_transaction("29_Reports tab",0);
	lr_start_transaction("30_Support Overview");
	truclient_step("54", "Click on SUPPORT link", "snapshot=Action_54.inf");
	truclient_step("55", "Wait for IN PROGRESS heading", "snapshot=Action_55.inf");
	truclient_step("56", "Wait for TOP 5 RESOLUTIONS heading", "snapshot=Action_56.inf");
	lr_end_transaction("30_Support Overview",0);
	lr_start_transaction("31_Support Ticket");
	truclient_step("57", "Click on Tickets link", "snapshot=Action_57.inf");
	truclient_step("58", "Wait for Ticket ID", "snapshot=Action_58.inf");
	lr_end_transaction("31_Support Ticket",0);
	truclient_step("59", "Click on LOCATIONS link", "snapshot=Action_59.inf");
	truclient_step("60", "Wait for Voice Trunking link", "snapshot=Action_60.inf");
	lr_start_transaction("14_Voice Trunking Tab");
	truclient_step("61", "Click on Voice Trunking link", "snapshot=Action_61.inf");
	truclient_step("62", "Wait for Account Number columnheader", "snapshot=Action_62.inf");
	lr_end_transaction("14_Voice Trunking Tab",0);
	lr_start_transaction("15_Voice Trunking Tab Non HiCap");
	truclient_step("63", "Click on Address / 1813 Spring... cell", "snapshot=Action_63.inf");
	truclient_step("64", "Wait for Trunk Group Number: 336... heading", "snapshot=Action_64.inf");
	lr_end_transaction("15_Voice Trunking Tab Non HiCap",0);
	lr_start_transaction("16_Voice Trunking Non HiCap View Charges");
	truclient_step("65", "Click on View Charges link", "snapshot=Action_65.inf");
	truclient_step("66", "Wait for Outbound Calls", "snapshot=Action_66.inf");
	lr_end_transaction("16_Voice Trunking Non HiCap View Charges",0);
	truclient_step("67", "Click on Back link", "snapshot=Action_67.inf");
	lr_start_transaction("17_Voice Trunking Non HiCap Plan Details");
	truclient_step("68", "Click on Plan Details link", "snapshot=Action_68.inf");
	truclient_step("69", "Wait for Blocked Numbers heading", "snapshot=Action_69.inf");
	lr_end_transaction("17_Voice Trunking Non HiCap Plan Details",0);
	truclient_step("70", "Click on Back link", "snapshot=Action_70.inf");
	lr_start_transaction("18_Non HiCap CDR Trunk");
	truclient_step("71", "Click on Call Detail Records link", "snapshot=Action_71.inf");
	truclient_step("72", "Wait for Duration columnheader", "snapshot=Action_72.inf");
	lr_end_transaction("18_Non HiCap CDR Trunk",0);
	lr_start_transaction("19_Non HiCap CDR Toll Free");
	truclient_step("73", "Click on Toll Free", "snapshot=Action_73.inf");
	truclient_step("74", "Wait for Duration columnheader", "snapshot=Action_74.inf");
	lr_end_transaction("19_Non HiCap CDR Toll Free",0);
	truclient_step("75", "Click on Back link", "snapshot=Action_75.inf");
	truclient_step("76", "Click on Back link", "snapshot=Action_76.inf");
	lr_start_transaction("20_Voice Trunking HiCap");
	truclient_step("77", "Click on Address / 1776 N Greenville... cell", "snapshot=Action_77.inf");
	truclient_step("78", "Wait for Trunk Group Number: 336... heading", "snapshot=Action_78.inf");
	lr_end_transaction("20_Voice Trunking HiCap",0);
	lr_start_transaction("21_Voice Trunking HiCap View Charges");
	truclient_step("79", "Click on View Charges link", "snapshot=Action_79.inf");
	truclient_step("80", "Wait for Duration columnheader", "snapshot=Action_80.inf");
	lr_end_transaction("21_Voice Trunking HiCap View Charges",0);
	truclient_step("81", "Click on Back link", "snapshot=Action_81.inf");
	lr_start_transaction("22_HiCap CDR Trunk");
	truclient_step("82", "Click on Call Detail Records link", "snapshot=Action_82.inf");
	truclient_step("83", "Wait for Duration columnheader", "snapshot=Action_83.inf");
	lr_end_transaction("22_HiCap CDR Trunk",0);
	lr_start_transaction("23_HiCap CDR Toll Free");
	truclient_step("84", "Click on Toll Free", "snapshot=Action_84.inf");
	truclient_step("85", "Wait for Duration columnheader", "snapshot=Action_85.inf");
	lr_end_transaction("23_HiCap CDR Toll Free",0);
	truclient_step("86", "Click on Back link", "snapshot=Action_86.inf");
	truclient_step("87", "Click on Back link", "snapshot=Action_87.inf");
	truclient_step("88", "Click on Account Number / 47796280... cell", "snapshot=Action_88.inf");
	lr_start_transaction("24_Voice CDR Create a Report");
	truclient_step("89", "Click on link (1) link", "snapshot=Action_89.inf");
	truclient_step("90", "Click on What type of Voice Trunking... button", "snapshot=Action_90.inf");
	lr_end_transaction("24_Voice CDR Create a Report",0);
	truclient_step("91", "Click on Start Date * textbox", "snapshot=Action_91.inf");
	truclient_step("92", "Type 10/29/2019 in Start Date * textbox", "snapshot=Action_92.inf");
	truclient_step("93", "Click on Data is available for...", "snapshot=Action_93.inf");
	lr_start_transaction("25_Non HiCap CMR");
	truclient_step("94", "Click on Submit button", "snapshot=Action_94.inf");
	lr_end_transaction("25_Non HiCap CMR",0);
	truclient_step("95", "Click on We're Preparing Your... button", "snapshot=Action_95.inf");
	truclient_step("96", "Click on link (1) link", "snapshot=Action_96.inf");
	truclient_step("97", "Wait 3 seconds", "snapshot=Action_97.inf");
	truclient_step("98", "Click on What type of Voice Trunking... label", "snapshot=Action_98.inf");
	truclient_step("99", "Wait 3 seconds", "snapshot=Action_99.inf");
	truclient_step("100", "Click on What type of Voice Trunking... button", "snapshot=Action_100.inf");
	truclient_step("101", "Click on 9/12/2019 10/11/2019", "snapshot=Action_101.inf");
	lr_start_transaction("26_Non HiCap CDR");
	truclient_step("102", "Click on Submit button", "snapshot=Action_102.inf");
	lr_end_transaction("26_Non HiCap CDR",0);
	truclient_step("103", "Click on We're Preparing Your... button", "snapshot=Action_103.inf");
	truclient_step("104", "Click on Back link", "snapshot=Action_104.inf");
	truclient_step("105", "Click on Account Number / 82601303... cell", "snapshot=Action_105.inf");
	truclient_step("106", "Click on link (1) link", "snapshot=Action_106.inf");
	truclient_step("107", "Click on What type of Voice Trunking... button", "snapshot=Action_107.inf");
	truclient_step("108", "Click on element (2)", "snapshot=Action_108.inf");
	truclient_step("109", "Click on M / 1 day", "snapshot=Action_109.inf");
	lr_start_transaction("27_Hi Cap CMR");
	truclient_step("110", "Click on Submit button", "snapshot=Action_110.inf");
	lr_end_transaction("27_Hi Cap CMR",0);
	truclient_step("111", "Click on We're Preparing Your... button", "snapshot=Action_111.inf");
	truclient_step("112", "Click on link (1) link", "snapshot=Action_112.inf");
	truclient_step("113", "Click on What type of Voice Trunking... label", "snapshot=Action_113.inf");
	truclient_step("114", "Click on What type of Voice Trunking... button", "snapshot=Action_114.inf");
	lr_start_transaction("28_Hi Cap CDR");
	truclient_step("115", "Click on Submit button", "snapshot=Action_115.inf");
	lr_end_transaction("28_Hi Cap CDR",0);
	truclient_step("116", "Click on We're Preparing Your... button", "snapshot=Action_116.inf");
	truclient_step("117", "Click on Z Perf test button", "snapshot=Action_117.inf");
	lr_start_transaction("32_Event Log");
	truclient_step("118", "Click on View Event Logs none", "snapshot=Action_118.inf");
	truclient_step("119", "Wait for Status button", "snapshot=Action_119.inf");
	lr_end_transaction("32_Event Log",0);
	truclient_step("120", "Click on Z Perf test button", "snapshot=Action_120.inf");
	lr_start_transaction("33_View User");
	truclient_step("121", "Click on View Users none", "snapshot=Action_121.inf");
	truclient_step("122", "Wait for perftest 041 link", "snapshot=Action_122.inf");
	lr_end_transaction("33_View User",0);
	truclient_step("123", "Click on perftest 041 link", "snapshot=Action_123.inf");
	truclient_step("124", "Wait for Username", "snapshot=Action_124.inf");
	lr_start_transaction("34_View User -Users Link");
	truclient_step("125", "Click on perftest 041 button", "snapshot=Action_125.inf");
	lr_end_transaction("34_View User -Users Link",0);
	truclient_step("126", "Click on Users link", "snapshot=Action_126.inf");
	truclient_step("127", "Click on LOCATIONS link", "snapshot=Action_127.inf");
	lr_start_transaction("36_Security Tab");
	truclient_step("128", "Click on Security link", "snapshot=Action_128.inf");
	lr_end_transaction("36_Security Tab",0);
	lr_start_transaction("37_Port Change");
	truclient_step("129", "Click on Policy Group 3 button", "snapshot=Action_129.inf");
	lr_end_transaction("37_Port Change",0);
	truclient_step("130", "Click on button (1) button", "snapshot=Action_130.inf");
	lr_start_transaction("38_ To Port");
	truclient_step("131", "Click on (Port2) link", "snapshot=Action_131.inf");
	lr_end_transaction("38_ To Port",0);
	truclient_step("132", "Click on Close button", "snapshot=Action_132.inf");
	lr_start_transaction("39_From Port");
	truclient_step("133", "Click on (Port3) link", "snapshot=Action_133.inf");
	lr_end_transaction("39_From Port",0);
	truclient_step("134", "Click on Close button", "snapshot=Action_134.inf");
	lr_start_transaction("40_Service Link");
	truclient_step("135", "Click on Quic443 (+1 ) link", "snapshot=Action_135.inf");
	lr_end_transaction("40_Service Link",0);
	truclient_step("136", "Click on Back button", "snapshot=Action_136.inf");
	truclient_step("137", "Click on Web Filter link", "snapshot=Action_137.inf");
	lr_start_transaction("41_Web Filter");
	truclient_step("138", "Click on Web Filters link", "snapshot=Action_138.inf");
	lr_end_transaction("41_Web Filter",0);
	truclient_step("139", "Click on Back button", "snapshot=Action_139.inf");
	truclient_step("140", "Click on Back button", "snapshot=Action_140.inf");
	lr_start_transaction("42_DNS Filter");
	truclient_step("141", "Click on DNS Filter link", "snapshot=Action_141.inf");
	lr_end_transaction("42_DNS Filter",0);
	truclient_step("142", "Scroll on Full Page Modal Card", "snapshot=Action_142.inf");
	truclient_step("143", "Click on Back button", "snapshot=Action_143.inf");
	truclient_step("144", "Click on Network link", "snapshot=Action_144.inf");
	truclient_step("145", "Click on Search address, city,... searchbox", "snapshot=Action_145.inf");
	truclient_step("146", "Type aws in Search address, city,... searchbox", "snapshot=Action_146.inf");
	truclient_step("147", "Click on 500 Mbps", "snapshot=Action_147.inf");
	lr_start_transaction("Cloud Gateway Details-AWS");
	truclient_step("148", "Click on Location: New York City,...", "snapshot=Action_148.inf");
	truclient_step("149", "Wait for Cloud Circuit ID 1 label", "snapshot=Action_149.inf");
	lr_end_transaction("Cloud Gateway Details-AWS",0);
	truclient_step("150", "Click on Back link", "snapshot=Action_150.inf");
	truclient_step("151", "Click on Search address, city,... searchbox", "snapshot=Action_151.inf");
	truclient_step("152", "Type azure in Search address, city,... searchbox", "snapshot=Action_152.inf");
	truclient_step("153", "Click on 1 Gbps", "snapshot=Action_153.inf");
	lr_start_transaction("Cloud Gateway Details-Azure");
	truclient_step("154", "Click on Location: Dallas, TXCloud...", "snapshot=Action_154.inf");
	truclient_step("155", "Wait for Cloud Circuit ID 1 label", "snapshot=Action_155.inf");
	lr_end_transaction("Cloud Gateway Details-Azure",0);
	truclient_step("156", "Click on perftest 081 button", "snapshot=Action_156.inf");
	lr_start_transaction("35_Sign Out");
	truclient_step("157", "Click on Sign Out button", "snapshot=Action_157.inf");
	truclient_step("158", "Wait for We've signed you out...", "snapshot=Action_158.inf");
	lr_end_transaction("35_Sign Out",0);

	return 0;
}
